/**
 * Parses markdown generated by the AI Assistant into structured blocks
 * according to the Persona and Response Structure.
 */

export interface ParsedBlock {
  type: 'core' | 'strengths' | 'gaps' | 'improvements' | 'critique' | 'next-step' | 'general';
  title?: string;
  content: string;
}

export function parseAssistantResponse(text: string): ParsedBlock[] {
  if (!text) return [];

  // Look for sections based on typical headers or bold titles:
  // e.g. ## Core Answer, **Core Answer:**, ## Strengths, **Strengths:**, etc.
  const lines = text.split('\n');
  const blocks: ParsedBlock[] = [];
  let currentType: ParsedBlock['type'] = 'general';
  let currentTitle: string | undefined = undefined;
  let currentContentLines: string[] = [];

  const flush = () => {
    if (currentContentLines.length > 0) {
      const content = currentContentLines.join('\n').trim();
      if (content) {
        blocks.push({
          type: currentType,
          title: currentTitle,
          content,
        });
      }
      currentContentLines = [];
    }
  };

  const isHeading = (line: string): { type: ParsedBlock['type']; title: string; remainder?: string } | null => {
    const trimmed = line.trim();
    
    // Test for Next Step / Elicitation
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Next Step|Next Steps|Follow-up Question|Elicitation|To Move Forward)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Next Step|Next Steps|Follow-up Question|Elicitation|To Move Forward)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'next-step', title: 'Next Step / Elicitation', remainder: match ? match[1] : '' };
    }

    // Test for Core Answer / Feedback
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Core Answer|Immediate Answer|Primary Feedback|Direct Answer)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Core Answer|Immediate Answer|Primary Feedback|Direct Answer)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'core', title: 'Core Answer & Feedback', remainder: match ? match[1] : '' };
    }

    // Test for Strengths
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Strengths|What's Working Well|Key Strengths)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Strengths|What's Working Well|Key Strengths)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'strengths', title: 'Strengths', remainder: match ? match[1] : '' };
    }

    // Test for Gaps or Risks
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Gaps or Risks|Gaps & Risks|Risks & Edge Cases|Identified Gaps|Edge Cases)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Gaps or Risks|Gaps & Risks|Risks & Edge Cases|Identified Gaps|Edge Cases)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'gaps', title: 'Gaps & Risks', remainder: match ? match[1] : '' };
    }

    // Test for Actionable Improvements
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Actionable Improvements|Concrete Recommendations|Recommended Improvements|Action Items)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Actionable Improvements|Concrete Recommendations|Recommended Improvements|Action Items)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'improvements', title: 'Actionable Improvements', remainder: match ? match[1] : '' };
    }

    // Test for Constructive Critique category headers
    if (/^(?:#{1,4}\s*)?(?:\*\*)?(?:Constructive Critique|Critique Breakdown|Evaluation Categories)(?:\*\*)?[:\?]?\s*(.*)$/i.test(trimmed)) {
      const match = trimmed.match(/^(?:#{1,4}\s*)?(?:\*\*)?(?:Constructive Critique|Critique Breakdown|Evaluation Categories)(?:\*\*)?[:\?]?\s*(.*)$/i);
      return { type: 'critique', title: 'Constructive Critique', remainder: match ? match[1] : '' };
    }

    return null;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const detected = isHeading(line);

    if (detected) {
      flush();
      currentType = detected.type;
      currentTitle = detected.title;
      if (detected.remainder && detected.remainder.trim().length > 0) {
        currentContentLines.push(detected.remainder.trim());
      }
    } else {
      currentContentLines.push(line);
    }
  }

  flush();

  // If no sections were identified, return the full text as general
  if (blocks.length === 0) {
    return [{ type: 'general', content: text }];
  }

  return blocks;
}
